const page=document.body.dataset.page||"home",headerMount=document.querySelector("[data-site-header]"),footerMount=document.querySelector("[data-site-footer]");
const navGroups=[
["home","Home",[["index.html","Overview"],["index.html#current-work","Current work"],["index.html#highlights","Highlights"]]],
["about","About Me",[["about.html","My story"],["about.html#education","Education"],["about.html#values","Values"],["assets/Eshan_Raul_Curriculum_Vitae.pdf","Curriculum vitae","external"]]],
["research","Research",[["research.html","Research overview"],["research-atmospheres.html","Atmospheres & retrievals"],["research-dynamics.html","Exoplanet dynamics"],["research-disks.html","Disk chemistry"]]],
["outreach","Outreach",[["outreach.html","Outreach overview"],["outreach.html#communication","Science communication"],["outreach.html#public-engagement","Public engagement"],["outreach.html#teaching","Teaching & mentorship"],["outreach.html#advocacy","Advocacy & service"]]],
["contact","Contact",[["contact.html","Get in touch"],["contact.html#collaborate","Research collaborations"],["contact.html#speaking","Speaking & media"],["mailto:eraul@wisc.edu","Email Eshan"]]]
];
const groups=navGroups.map(g=>'<div class="nav-group '+(g[0]===page?"is-current":"")+'"><button class="nav-trigger" type="button" aria-expanded="false">'+g[1]+'<span aria-hidden="true">⌄</span></button><div class="dropdown-menu">'+g[2].map(i=>'<a href="'+i[0]+'"'+(i[2]?' target="_blank"':'')+'>'+i[1]+'</a>').join("")+'</div></div>').join("");
headerMount.innerHTML='<a class="skip-link" href="#main-content">Skip to content</a><header class="site-header"><a class="brand" href="index.html" aria-label="Eshan Raul home"><span class="brand-mark" aria-hidden="true"></span><span>ESHAN RAUL</span></a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="site-nav"><span></span><span></span><span class="sr-only">Toggle navigation</span></button><nav class="site-nav" id="site-nav" aria-label="Main navigation">'+groups+'</nav></header>';
footerMount.innerHTML='<footer class="site-footer"><p>© <span data-year></span> Eshan Raul</p><p>Astronomy · Exoplanets · Science communication</p><div class="footer-links"><a href="https://orcid.org/0009-0002-2380-6683" target="_blank" rel="noreferrer">ORCID</a><a href="https://www.researchgate.net/profile/Eshan-Raul" target="_blank" rel="noreferrer">ResearchGate</a><a href="https://www.linkedin.com/in/eshanraul/" target="_blank" rel="noreferrer">LinkedIn</a></div></footer>';
document.querySelector("[data-year]").textContent=new Date().getFullYear();
const header=document.querySelector(".site-header"),menu=document.querySelector(".menu-toggle"),nav=document.querySelector(".site-nav"),triggers=[...document.querySelectorAll(".nav-trigger")];
function closeDropdowns(except){triggers.forEach(t=>{if(t!==except){t.parentElement.classList.remove("open");t.setAttribute("aria-expanded","false")}})}
menu.addEventListener("click",()=>{const open=nav.classList.toggle("open");menu.setAttribute("aria-expanded",String(open));if(!open)closeDropdowns()});
triggers.forEach(t=>t.addEventListener("click",e=>{e.stopPropagation();const open=!t.parentElement.classList.contains("open");closeDropdowns(t);t.parentElement.classList.toggle("open",open);t.setAttribute("aria-expanded",String(open))}));
document.addEventListener("click",()=>closeDropdowns());document.addEventListener("keydown",e=>{if(e.key==="Escape"){closeDropdowns();nav.classList.remove("open");menu.setAttribute("aria-expanded","false")}});
addEventListener("resize",()=>{if(innerWidth>980){nav.classList.remove("open");menu.setAttribute("aria-expanded","false")}});
function updateHeader(){header.classList.toggle("scrolled",scrollY>18)}addEventListener("scroll",updateHeader,{passive:true});updateHeader();
const reduceMotion=matchMedia("(prefers-reduced-motion: reduce)").matches,canvas=document.querySelector("#starfield"),ctx=canvas.getContext("2d");let stars=[],vw=0,vh=0,pointerX=0,pointerY=0;
function resizeCanvas(){const dpr=Math.min(devicePixelRatio||1,2);vw=innerWidth;vh=innerHeight;canvas.width=vw*dpr;canvas.height=vh*dpr;canvas.style.width=vw+"px";canvas.style.height=vh+"px";ctx.setTransform(dpr,0,0,dpr,0,0);const n=Math.min(Math.max(Math.floor(vw*vh/4200),120),300);stars=Array.from({length:n},(_,i)=>{const d=.2+Math.random()*.8;return{x:Math.random()*vw,y:Math.random()*vh,r:.45+d*1.15,a:.34+Math.random()*.55,t:.004+Math.random()*.009,dir:i%2?1:-1,d,blue:Math.random()>.86}})}
function drawStars(){ctx.clearRect(0,0,vw,vh);const shift=scrollY*.11;stars.forEach(s=>{const x=(s.x+pointerX*s.d+vw)%vw,y=(s.y+shift*s.d+pointerY*s.d+vh)%vh;ctx.beginPath();ctx.arc(x,y,s.r,0,Math.PI*2);ctx.fillStyle=s.blue?"rgba(20,177,201,"+Math.min(s.a+.12,1)+")":"rgba(225,238,255,"+s.a+")";ctx.fill();if(!reduceMotion){s.a+=s.t*s.dir;if(s.a>.92||s.a<.28)s.dir*=-1}});if(!reduceMotion)requestAnimationFrame(drawStars)}
addEventListener("pointermove",e=>{pointerX=(e.clientX/vw-.5)*-18;pointerY=(e.clientY/vh-.5)*-12},{passive:true});addEventListener("resize",()=>{resizeCanvas();if(reduceMotion)drawStars()});resizeCanvas();drawStars();
const reveals=document.querySelectorAll(".reveal");if("IntersectionObserver"in window&&!reduceMotion){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("visible");observer.unobserve(entry.target)}}),{threshold:.1});reveals.forEach((el,i)=>{el.style.transitionDelay=Math.min(i%3,2)*80+"ms";observer.observe(el)})}else reveals.forEach(el=>el.classList.add("visible"));
const modeButtons=[...document.querySelectorAll("[data-research-mode]")];function setMode(mode){document.documentElement.dataset.researchMode=mode;modeButtons.forEach(b=>{const active=b.dataset.researchMode===mode;b.classList.toggle("active",active);b.setAttribute("aria-pressed",String(active))});try{localStorage.setItem("eshan-research-mode",mode)}catch(e){}}
if(modeButtons.length){let saved="simple";try{saved=localStorage.getItem("eshan-research-mode")||"simple"}catch(e){}setMode(saved==="scientific"?"scientific":"simple");modeButtons.forEach(b=>b.addEventListener("click",()=>setMode(b.dataset.researchMode)))}
