const canvas=document.querySelector("#starfield"),ctx=canvas.getContext("2d"),reduceMotion=matchMedia("(prefers-reduced-motion: reduce)").matches;
let stars=[],width=0,height=0,mouseX=0,mouseY=0;
function resizeCanvas(){const dpr=Math.min(devicePixelRatio||1,2);width=innerWidth;height=innerHeight;canvas.width=width*dpr;canvas.height=height*dpr;canvas.style.width=width+"px";canvas.style.height=height+"px";ctx.setTransform(dpr,0,0,dpr,0,0);const count=Math.min(Math.floor(width*height/5600),220);stars=Array.from({length:count},()=>({x:Math.random()*width,y:Math.random()*height,r:Math.random()*1.15+.15,a:Math.random()*.65+.15,s:Math.random()*.08+.015,d:Math.random()*.8+.2}))}
function drawStars(){ctx.clearRect(0,0,width,height);const shift=scrollY*.025;stars.forEach(star=>{const x=star.x+mouseX*star.d,y=(star.y+shift*star.d)%height+mouseY*star.d;ctx.beginPath();ctx.arc(x,y,star.r,0,Math.PI*2);ctx.fillStyle=`rgba(220,238,255,${star.a})`;ctx.fill();if(!reduceMotion){star.a+=star.s*.01;if(star.a>.85||star.a<.12)star.s*=-1}});if(!reduceMotion)requestAnimationFrame(drawStars)}
addEventListener("resize",()=>{resizeCanvas();if(reduceMotion)drawStars()});addEventListener("mousemove",e=>{mouseX=(e.clientX/width-.5)*-8;mouseY=(e.clientY/height-.5)*-8});resizeCanvas();drawStars();
const header=document.querySelector(".site-header"),menuButton=document.querySelector(".menu-toggle"),nav=document.querySelector(".site-nav");
function updateHeader(){header.classList.toggle("scrolled",scrollY>20)}addEventListener("scroll",updateHeader,{passive:true});updateHeader();
menuButton.addEventListener("click",()=>{const open=nav.classList.toggle("open");menuButton.setAttribute("aria-expanded",String(open))});nav.querySelectorAll("a").forEach(link=>link.addEventListener("click",()=>{nav.classList.remove("open");menuButton.setAttribute("aria-expanded","false")}));
const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("visible");revealObserver.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll(".reveal").forEach((el,i)=>{el.style.transitionDelay=Math.min(i%3,2)*90+"ms";revealObserver.observe(el)});
const sections=[...document.querySelectorAll("main section[id]")],navLinks=[...nav.querySelectorAll("a")];const sectionObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)navLinks.forEach(link=>link.classList.toggle("active",link.hash==="#"+entry.target.id))}),{rootMargin:"-35% 0px -55% 0px"});sections.forEach(section=>sectionObserver.observe(section));document.querySelector("#year").textContent=new Date().getFullYear();
